project:
  type: website

website:
  title: "istio.wtf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    mainfont:  "Consolas, monospace"
