project:
  type: website

website:
  title: "istio.wtf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  page-footer:
    center: "Copyright 2024-2025, [Progredo Systems Inc.](https://progredo.ca)"

format:
  html:
    # direct pandoc options
    toc: true
    from: markdown-smart
    css: styles.css
    # quarto options
    theme: litera
    mainfont:  "Consolas, monospace"
    page-layout: full
